title: Yue (Yula) Yu's Homepage
page-top-title: Yue (Yula) Yu
top-section-bg-text: Electrical Engineering
home-subtitle: Yue (Yula) Yu &  | 俞越
copyright-text: '&copy; Yue (Yula) Yu 2025-2026. All Rights Reserved.'
